/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category {
  'id' : bigint,
  'sortOrder' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
}
export interface GalleryItem {
  'id' : bigint,
  'sortOrder' : bigint,
  'imageUrl' : string,
  'caption' : string,
  'itemType' : string,
}
export interface Inquiry {
  'id' : bigint,
  'status' : string,
  'country' : string,
  'name' : string,
  'createdAt' : bigint,
  'whatsapp' : string,
  'productId' : [] | [bigint],
  'requirement' : string,
}
export interface Product {
  'id' : bigint,
  'moq' : string,
  'categoryId' : bigint,
  'featured' : boolean,
  'imageUrls' : Array<string>,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
}
export interface Testimonial {
  'id' : bigint,
  'active' : boolean,
  'country' : string,
  'name' : string,
  'text' : string,
  'company' : string,
  'rating' : bigint,
}
export interface UserProfile {
  'country' : string,
  'name' : string,
  'company' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCategory' : ActorMethod<[string, string, string, bigint], bigint>,
  'createGalleryItem' : ActorMethod<[string, string, string, bigint], bigint>,
  'createProduct' : ActorMethod<
    [bigint, string, string, string, Array<string>, boolean],
    bigint
  >,
  'createTestimonial' : ActorMethod<
    [string, string, string, string, bigint, boolean],
    bigint
  >,
  'deleteCategory' : ActorMethod<[bigint], undefined>,
  'deleteGalleryItem' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'deleteTestimonial' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getContent' : ActorMethod<[string], [] | [string]>,
  'getDashboardStats' : ActorMethod<
    [],
    {
      'totalProducts' : bigint,
      'newInquiries' : bigint,
      'totalVisits' : bigint,
      'totalInquiries' : bigint,
    }
  >,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getGallery' : ActorMethod<[[] | [string]], Array<GalleryItem>>,
  'getInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProducts' : ActorMethod<[[] | [bigint]], Array<Product>>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'verifyAdminLogin' : ActorMethod<[string, string], boolean>,
  'changeAdminCredentials' : ActorMethod<[string, string, string, string], boolean>,
  'recordVisit' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setContent' : ActorMethod<[string, string], undefined>,
  'submitInquiry' : ActorMethod<
    [string, string, string, string, [] | [bigint]],
    bigint
  >,
  'updateCategory' : ActorMethod<
    [bigint, string, string, string, bigint],
    undefined
  >,
  'updateGalleryItem' : ActorMethod<
    [bigint, string, string, string, bigint],
    undefined
  >,
  'updateInquiryStatus' : ActorMethod<[bigint, string], undefined>,
  'updateProduct' : ActorMethod<
    [bigint, bigint, string, string, string, Array<string>, boolean],
    undefined
  >,
  'updateTestimonial' : ActorMethod<
    [bigint, string, string, string, string, bigint, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];