/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : bigint,
  'status' : string,
  'title' : string,
  'content' : string,
  'date' : string,
  'createdAt' : bigint,
  'slug' : string,
  'author' : string,
  'readTime' : string,
  'excerpt' : string,
  'category' : string,
  'image' : string,
}
export interface Catalogue {
  'id' : bigint,
  'title' : string,
  'createdAt' : bigint,
  'description' : string,
  'fileName' : string,
  'uploadedAt' : string,
  'fileUrl' : string,
}
export interface Category {
  'id' : bigint,
  'sortOrder' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
}
export interface GalleryItem {
  'id' : bigint,
  'sortOrder' : bigint,
  'imageUrl' : string,
  'caption' : string,
  'itemType' : string,
}
export interface Inquiry {
  'id' : bigint,
  'status' : string,
  'country' : string,
  'name' : string,
  'createdAt' : bigint,
  'whatsapp' : string,
  'productId' : [] | [bigint],
  'requirement' : string,
}
export interface Product {
  'id' : bigint,
  'moq' : string,
  'categoryId' : bigint,
  'featured' : boolean,
  'imageUrls' : Array<string>,
  'name' : string,
  'createdAt' : bigint,
  'isNewArrival' : boolean,
  'description' : string,
}
export interface Testimonial {
  'id' : bigint,
  'active' : boolean,
  'country' : string,
  'name' : string,
  'text' : string,
  'company' : string,
  'rating' : bigint,
}
export interface UserProfile {
  'country' : string,
  'name' : string,
  'company' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'changeAdminCredentials' : ActorMethod<
    [string, string, string, string],
    boolean
  >,
  'createBlogPost' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    bigint
  >,
  'createCatalogue' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'createCategory' : ActorMethod<[string, string, string, bigint], bigint>,
  'createGalleryItem' : ActorMethod<[string, string, string, bigint], bigint>,
  'createProduct' : ActorMethod<
    [bigint, string, string, string, Array<string>, boolean, boolean],
    bigint
  >,
  'createTestimonial' : ActorMethod<
    [string, string, string, string, bigint, boolean],
    bigint
  >,
  'deleteBlogPost' : ActorMethod<[bigint], undefined>,
  'deleteCatalogue' : ActorMethod<[bigint], undefined>,
  'deleteCategory' : ActorMethod<[bigint], undefined>,
  'deleteGalleryItem' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'deleteTestimonial' : ActorMethod<[bigint], undefined>,
  'getBlogPost' : ActorMethod<[string], [] | [BlogPost]>,
  'getBlogPosts' : ActorMethod<[[] | [string]], Array<BlogPost>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCatalogues' : ActorMethod<[], Array<Catalogue>>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getContent' : ActorMethod<[string], [] | [string]>,
  'getDashboardStats' : ActorMethod<
    [],
    {
      'totalProducts' : bigint,
      'newInquiries' : bigint,
      'totalVisits' : bigint,
      'totalInquiries' : bigint,
    }
  >,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getGallery' : ActorMethod<[[] | [string]], Array<GalleryItem>>,
  'getInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getNewArrivalProducts' : ActorMethod<[], Array<Product>>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProducts' : ActorMethod<[[] | [bigint]], Array<Product>>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordVisit' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setContent' : ActorMethod<[string, string], undefined>,
  'submitInquiry' : ActorMethod<
    [string, string, string, string, [] | [bigint]],
    bigint
  >,
  'updateBlogPost' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    undefined
  >,
  'updateCategory' : ActorMethod<
    [bigint, string, string, string, bigint],
    undefined
  >,
  'updateGalleryItem' : ActorMethod<
    [bigint, string, string, string, bigint],
    undefined
  >,
  'updateInquiryStatus' : ActorMethod<[bigint, string], undefined>,
  'updateProduct' : ActorMethod<
    [bigint, bigint, string, string, string, Array<string>, boolean, boolean],
    undefined
  >,
  'updateTestimonial' : ActorMethod<
    [bigint, string, string, string, string, bigint, boolean],
    undefined
  >,
  'verifyAdminLogin' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];